### PR TITLE
Add support for a --start_id flag

### PR DESCRIPTION
**Pull request by netaustin**
...ost ID.

### CODE REVIEW

**Comment by mjangda** [comment]
What's the use case for this?

**Comment by netaustin** [comment]
To generate a delta XML file for wpcom import.

On Tue, Apr 24, 2012 at 4:11 PM, Mohammad Jangda <
reply@reply.github.com

**Comment by mjangda** [comment]
start_date is more reliable for generating deltas. A higher ID doesn't always guarantee a newer post.

**Comment by netaustin** [comment]
Hmm. Then maybe an enhancement to set that to a particular time would be
useful.

On Tue, Apr 24, 2012 at 5:00 PM, Mohammad Jangda <
reply@reply.github.com

**Comment by mjangda** [comment]
Yep, that would be a much nicer enhancement. Want to give that a shot instead?

**Pull request closed without merging**
